### ISSUE TITLE
Enhanced product export never ends

### ISSUE THREAD

**Issue by ghost** [akeneo-labs/EnhancedConnectorBundle#34] opened 2015-11-24 11:10 UTC
Hi,

 I have a problem with the Enhanced connector bundle, it is still running even after finishing to export. The export has a status "Terminated" and status "Started" in Akeneo, so if we stop the task the status is "failed" and "terminated" So we have two differents status for one export (see below).

![be303f12 8e09 11e5 9da7 04fa5f779d7d](https://cloud.githubusercontent.com/assets/13782236/11364493/18027488-92a1-11e5-86d9-6bb01781179c.png)

Regards.

**Comment by ghost** [comment] 2015-11-30 09:17
Hello,

I come back to you because this problem with the export is getting worst;
This weekend, the export used all the RAM and almost all SWAP on the server

```
$:~# free -m |egrep "Swap|Mem|free"
                      total       used       free     shared    buffers     cached
Mem:         31924      29743       2181        451        107       3020
Swap:        16071      13781       2290
```

We found our the problem is the Enhanced product export

```
/usr/sbin/cron
 \_ /USR/SBIN/CRON
 |   \_ /bin/sh -c cd /var/www/akeneo; php app/console akeneo:batch:job enhanced_products_export
 |       \_ php app/console akeneo:batch:job enhanced_products_export
 |   \_ /bin/sh -c cd /var/www/akeneo; php app/console akeneo:batch:job enhanced_products_export
 |       \_ php app/console akeneo:batch:job enhanced_products_export
  |   \_ /bin/sh -c cd /var/www/akeneo; php app/console akeneo:batch:job enhanced_products_export
 |       \_ php app/console akeneo:batch:job enhanced_products_export
```

The exports never stops and one ran 307 hours without ending.

Can you please help us.

Regards.

**Comment by damien-carcel** [comment] 2015-11-30 09:49
Hello.

How much product did you export?

I see in your CRON configuration that you run your exports in dev mode, which cause huge memory leaks. Change you commands for:

```
php app/console --env=prod akeneo:batch:job ***
```

Another thing: check that you don't have XDebug active (also cause memory leaks).

I couldn't reproduce your status bug, and don't have much time to check further right now. I will investigate it again as soon as I can.

Regards,
Damien

**Comment by ghost** [comment] 2015-11-30 10:21
Hi,

Thanks for your feedback. 
We export maximum 12k products. I will specify the prod environment and see if it improves performances.

For the status inconsistency I will try to get more informations.

Regards.

**Comment by damien-carcel** [comment] 2015-12-02 11:02
Hello. A memory leak issue has been fixed on PIM exports, which also affect this connector.

It has been fixed on both Akeneo 1.4.9 and 1.3.32 (you can see the PR on 1.4 [here](https://github.com/akeneo/pim-community-dev/pull/3559/files)).

Please check if your problem is solved by updating to the last version of the PIM.

Regards,
Damien

**Comment by damien-carcel** [comment] 2016-01-04 08:55
Hello @gaces 

I have been able to reproduce your bug (by accident, in fact), and I can confirm it happens when the memory usage is too high. I also confirm that it should not happen anymore with last Akeneo versions and the memory leak fixed.

Regards,
Damien

**Comment by damien-carcel** [comment] 2016-01-11 10:04
Hello @gaces.

Version 1.0.5 of the connector fixes a memory leak on product export. It could fix your problem too.

Regards,
Damien

**Comment by bhouillon** [comment] 2016-01-29 09:16
Hello @damien-carcel 

I have the same problem as @gaces. I'm on Akeneo EE 1.4.16 with Enhanced Connector 1.1.0 and MongoDB,  the product export never ends. I'm trying to export around 16 000 products, and like him I have two status for one export, completed and failed. It failed when allowed memory size is exhausted.

Regards.

**Comment by fitn** [comment] 2016-02-03 10:46
Hi,

Thank you for raising this issue.
We're currently working on this memory leak and we will release a new version when it will be fixed.

Regards,

**Comment by fitn** [comment] 2016-02-17 14:19
Hi @bhouillon 

Finally we reproduced. It comes from the archive generated at the end of the job which take to much memory when you have medias.
The archive is done on a subscriber so that's why the step is completed but the job is failed ;)

A PIM ticket has been created on that subject so I close this ticket.

Regards,

**Closed as completed by fitn** 2016-02-17 14:19 UTC
Labels: bug
