### ISSUE TITLE
The media has not been found

### ISSUE THREAD

**Issue by akkermanronald** [akeneo-labs/EnhancedConnectorBundle#36] opened 2015-12-01 09:27 UTC
After upgrading to 1.03 (first removed the old version) and combined with Akeneo 1.4.11 we are getting the error message below for all products. The filepath and file exist though. The destination path and folders are also created but no pictures placed in them. 

<img width="541" alt="schermafdruk 2015-12-01 10 17 02" src="https://cloud.githubusercontent.com/assets/15016164/11496926/b6ba9d16-9815-11e5-9acf-7498deebddfb.png">

**Comment by damien-carcel** [comment] 2015-12-07 17:10
Hello.

I'm sorry, but I cannot reproduce this behavior. I can obtain the same error message as you, but in this case, the file is really missing. If the file is present in my file system, then I obtain an ZIP archive containing the CSV file and the media.

Are you sure the file is present inside "app/file_storage/catalog/8/3/4/e/", and possesses the exact same name?

Regards,
Damien

**Comment by Valentyn-Kubrak** [comment] 2015-12-31 13:38
@akkermanronald ,
I faced with the same problem. I think if you will run Akeneo PIM using app_dev.php file, you will see error that  your app can't create folder. Because by default it working with folder /tmp/pim. Please check permissions of this folder.

@damien-carcel 
 Dear Damien, can you please help me:
1) how  can I see stack traces when something happened, batch logs does't tell anything , I want to see exceptions traces like in Magento.  
2) How I can customize  path of folder for saving export file in admin panel?

**Comment by damien-carcel** [comment] 2016-01-04 09:00
Hello Valentyn.

You should have access to stack traces in app/logs/dev.log (or prod.log). If there is nothing here, then you should have something in apache logs.

If there is nothing, then you probably have an error without exception (rare, but can happen), and there is not much to do about it, sadly…

Regards,
Damien

**Comment by Valentyn-Kubrak** [comment] 2016-01-05 11:18
@akkermanronald thanks for your answer.
Is there are some way to output stack traces in batch logs when something happened? I think  when you catching exceptions it's better to show it in batch logs.

**Comment by akkermanronald** [comment] 2016-01-05 11:29
I don't know, you need feedback from the Akeneo labs team on that one. We have seen permissions issues on the subfolders (prod and dev) in the cache folder, which are not being deleted even if we carried out sudo rm -rf /app/cache/\*  This has also caused us headache when carrying out upgrades and could also be related to the original post here. Recent attempts to upgrade from 1.4.10 to higher versions have been particularly painful in this regard, having to revert system images back to 1.4.10 each time, despite several attempts to clear all caches and resetting permissions.

**Comment by damien-carcel** [comment] 2016-01-05 12:59
@akkermanronald the permission problem you refer to is in general a consequence of a bad apache user setting. We recommend in the [PIM installation documentation](http://docs.akeneo.com/latest/developer_guide/installation/installation_workstation.html#apache) to set apache user/group identical to the default user/group you use to access the pim install (when you update with composer, for instance), so there is no permission conflicts.

@Valentyn-Kubrak you can add logs in your own developments. This is provided not by the Enhanced connector itself, but by the [batch bundle](https://github.com/akeneo/BatchBundle), which provide the base code for all import/export in Akeneo.
You can see an example in the processor of the product import of the PIM: [here](https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php#L99) an exception is launched with a method defined in the [AbstractProcessor](https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Component/Connector/Processor/Denormalization/AbstractProcessor.php#L93), which use an [exception class from the batch bundle](https://github.com/akeneo/BatchBundle/blob/master/Item/InvalidItemException.php). Then this exception will be caught by monolog and add to batch_execute.log.

If you don’t have any message in the logs, that can mean two things:
- neither Akeneo nor Symfony catch the exception, which to me seems very unlikely,
- or there is no exception launched when your problem occurs (which is probably the best explanation), so you have to find where it happens (difficult without stack trace, I admit) and add a try/catch.

@akkermanronald again: is your problem still on, or have you solved it with better permission settings?

@Valentyn-Kubrak: if you want to discuss this log issue further, please open a new issue, so we do not “pollute” this post, I will then delete my answers regarding it from here and add it to your new post.

Regards,
Damien

**Comment by fitn** [comment] 2016-02-17 14:45
Hi guys,

I close this issue as there is no discussion still more than one month. You can reopen the issue if your issues are not resolved ;)

Regards,
Romain

**Closed as completed by fitn** 2016-02-17 14:45 UTC
Labels: bug
